export const pages = [
    "https://dealerportal.kalyanicrm.com/dashboard",
    "https://dealerportal.kalyanicrm.com/marketplace",
    "https://dealerportal.kalyanicrm.com/wishlist",
    "https://dealerportal.kalyanicrm.com/deals",
    "https://dealerportal.kalyanicrm.com/awards",
    "https://dealerportal.kalyanicrm.com/referrals",
    "https://dealerportal.kalyanicrm.com/profile",
    "https://dealerportal.kalyanicrm.com/rc-follow-ups",
    "https://dealerportal.kalyanicrm.com/account-balance",
    "https://dealerportal.kalyanicrm.com/referrals/new",
    "https://dealerportal.kalyanicrm.com/marketplace/events/0a37f96c-a87f-491c-b992-d504fa796fed?lane=parallel",
    "https://dealerportal.kalyanicrm.com/marketplace/8cd54cb6-a658-4831-a1c2-10f675c7b6d7?eventId=0a37f96c-a87f-491c-b992-d504fa796fed&lane=parallel",
    "https://dealerportal.kalyanicrm.com/awards/6dbe161f-9c43-4bbe-963d-d341ae7bc0be",
    "https://dealerportal.kalyanicrm.com/deals/363edacf-181b-4625-ae7d-9202c1619c85",
]
